/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRaniRouteImport } from './routes/_authenticated.rani'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated.perfil'
import { Route as AuthenticatedNotasRouteImport } from './routes/_authenticated.notas'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated.financeiro'
import { Route as AuthenticatedFaturamentoRouteImport } from './routes/_authenticated.faturamento'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated.equipe'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAvisosRouteImport } from './routes/_authenticated.avisos'
import { Route as AuthenticatedAtividadeRouteImport } from './routes/_authenticated.atividade'
import { Route as AuthenticatedArquivosRouteImport } from './routes/_authenticated.arquivos'
import { Route as AuthenticatedRaniIndexRouteImport } from './routes/_authenticated.rani.index'
import { Route as AuthenticatedProjetosIndexRouteImport } from './routes/_authenticated.projetos.index'
import { Route as AuthenticatedRaniThreadIdRouteImport } from './routes/_authenticated.rani.$threadId'
import { Route as AuthenticatedProjetosIdRouteImport } from './routes/_authenticated.projetos.$id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRaniRoute = AuthenticatedRaniRouteImport.update({
  id: '/rani',
  path: '/rani',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotasRoute = AuthenticatedNotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFaturamentoRoute =
  AuthenticatedFaturamentoRouteImport.update({
    id: '/faturamento',
    path: '/faturamento',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAvisosRoute = AuthenticatedAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAtividadeRoute = AuthenticatedAtividadeRouteImport.update({
  id: '/atividade',
  path: '/atividade',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArquivosRoute = AuthenticatedArquivosRouteImport.update({
  id: '/arquivos',
  path: '/arquivos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRaniIndexRoute = AuthenticatedRaniIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRaniRoute,
} as any)
const AuthenticatedProjetosIndexRoute =
  AuthenticatedProjetosIndexRouteImport.update({
    id: '/projetos/',
    path: '/projetos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRaniThreadIdRoute =
  AuthenticatedRaniThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedRaniRoute,
  } as any)
const AuthenticatedProjetosIdRoute = AuthenticatedProjetosIdRouteImport.update({
  id: '/projetos/$id',
  path: '/projetos/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arquivos': typeof AuthenticatedArquivosRoute
  '/atividade': typeof AuthenticatedAtividadeRoute
  '/avisos': typeof AuthenticatedAvisosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/faturamento': typeof AuthenticatedFaturamentoRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/notas': typeof AuthenticatedNotasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/rani': typeof AuthenticatedRaniRouteWithChildren
  '/projetos/$id': typeof AuthenticatedProjetosIdRoute
  '/rani/$threadId': typeof AuthenticatedRaniThreadIdRoute
  '/projetos/': typeof AuthenticatedProjetosIndexRoute
  '/rani/': typeof AuthenticatedRaniIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arquivos': typeof AuthenticatedArquivosRoute
  '/atividade': typeof AuthenticatedAtividadeRoute
  '/avisos': typeof AuthenticatedAvisosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/faturamento': typeof AuthenticatedFaturamentoRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/notas': typeof AuthenticatedNotasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/projetos/$id': typeof AuthenticatedProjetosIdRoute
  '/rani/$threadId': typeof AuthenticatedRaniThreadIdRoute
  '/projetos': typeof AuthenticatedProjetosIndexRoute
  '/rani': typeof AuthenticatedRaniIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/arquivos': typeof AuthenticatedArquivosRoute
  '/_authenticated/atividade': typeof AuthenticatedAtividadeRoute
  '/_authenticated/avisos': typeof AuthenticatedAvisosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/faturamento': typeof AuthenticatedFaturamentoRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/notas': typeof AuthenticatedNotasRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/rani': typeof AuthenticatedRaniRouteWithChildren
  '/_authenticated/projetos/$id': typeof AuthenticatedProjetosIdRoute
  '/_authenticated/rani/$threadId': typeof AuthenticatedRaniThreadIdRoute
  '/_authenticated/projetos/': typeof AuthenticatedProjetosIndexRoute
  '/_authenticated/rani/': typeof AuthenticatedRaniIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arquivos'
    | '/atividade'
    | '/avisos'
    | '/dashboard'
    | '/equipe'
    | '/faturamento'
    | '/financeiro'
    | '/notas'
    | '/perfil'
    | '/rani'
    | '/projetos/$id'
    | '/rani/$threadId'
    | '/projetos/'
    | '/rani/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arquivos'
    | '/atividade'
    | '/avisos'
    | '/dashboard'
    | '/equipe'
    | '/faturamento'
    | '/financeiro'
    | '/notas'
    | '/perfil'
    | '/projetos/$id'
    | '/rani/$threadId'
    | '/projetos'
    | '/rani'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/arquivos'
    | '/_authenticated/atividade'
    | '/_authenticated/avisos'
    | '/_authenticated/dashboard'
    | '/_authenticated/equipe'
    | '/_authenticated/faturamento'
    | '/_authenticated/financeiro'
    | '/_authenticated/notas'
    | '/_authenticated/perfil'
    | '/_authenticated/rani'
    | '/_authenticated/projetos/$id'
    | '/_authenticated/rani/$threadId'
    | '/_authenticated/projetos/'
    | '/_authenticated/rani/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rani': {
      id: '/_authenticated/rani'
      path: '/rani'
      fullPath: '/rani'
      preLoaderRoute: typeof AuthenticatedRaniRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notas': {
      id: '/_authenticated/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof AuthenticatedNotasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/faturamento': {
      id: '/_authenticated/faturamento'
      path: '/faturamento'
      fullPath: '/faturamento'
      preLoaderRoute: typeof AuthenticatedFaturamentoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/avisos': {
      id: '/_authenticated/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AuthenticatedAvisosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/atividade': {
      id: '/_authenticated/atividade'
      path: '/atividade'
      fullPath: '/atividade'
      preLoaderRoute: typeof AuthenticatedAtividadeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/arquivos': {
      id: '/_authenticated/arquivos'
      path: '/arquivos'
      fullPath: '/arquivos'
      preLoaderRoute: typeof AuthenticatedArquivosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rani/': {
      id: '/_authenticated/rani/'
      path: '/'
      fullPath: '/rani/'
      preLoaderRoute: typeof AuthenticatedRaniIndexRouteImport
      parentRoute: typeof AuthenticatedRaniRoute
    }
    '/_authenticated/projetos/': {
      id: '/_authenticated/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof AuthenticatedProjetosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rani/$threadId': {
      id: '/_authenticated/rani/$threadId'
      path: '/$threadId'
      fullPath: '/rani/$threadId'
      preLoaderRoute: typeof AuthenticatedRaniThreadIdRouteImport
      parentRoute: typeof AuthenticatedRaniRoute
    }
    '/_authenticated/projetos/$id': {
      id: '/_authenticated/projetos/$id'
      path: '/projetos/$id'
      fullPath: '/projetos/$id'
      preLoaderRoute: typeof AuthenticatedProjetosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRaniRouteChildren {
  AuthenticatedRaniThreadIdRoute: typeof AuthenticatedRaniThreadIdRoute
  AuthenticatedRaniIndexRoute: typeof AuthenticatedRaniIndexRoute
}

const AuthenticatedRaniRouteChildren: AuthenticatedRaniRouteChildren = {
  AuthenticatedRaniThreadIdRoute: AuthenticatedRaniThreadIdRoute,
  AuthenticatedRaniIndexRoute: AuthenticatedRaniIndexRoute,
}

const AuthenticatedRaniRouteWithChildren =
  AuthenticatedRaniRoute._addFileChildren(AuthenticatedRaniRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedArquivosRoute: typeof AuthenticatedArquivosRoute
  AuthenticatedAtividadeRoute: typeof AuthenticatedAtividadeRoute
  AuthenticatedAvisosRoute: typeof AuthenticatedAvisosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedFaturamentoRoute: typeof AuthenticatedFaturamentoRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedNotasRoute: typeof AuthenticatedNotasRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRaniRoute: typeof AuthenticatedRaniRouteWithChildren
  AuthenticatedProjetosIdRoute: typeof AuthenticatedProjetosIdRoute
  AuthenticatedProjetosIndexRoute: typeof AuthenticatedProjetosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedArquivosRoute: AuthenticatedArquivosRoute,
  AuthenticatedAtividadeRoute: AuthenticatedAtividadeRoute,
  AuthenticatedAvisosRoute: AuthenticatedAvisosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedFaturamentoRoute: AuthenticatedFaturamentoRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedNotasRoute: AuthenticatedNotasRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRaniRoute: AuthenticatedRaniRouteWithChildren,
  AuthenticatedProjetosIdRoute: AuthenticatedProjetosIdRoute,
  AuthenticatedProjetosIndexRoute: AuthenticatedProjetosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
